version: "3.7"

services:
  rentalx-postgres:
    image: postgres
    container_name: rentalx-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local